import os
import subprocess
from pathlib import Path
from typing import Optional

from .config import ClaudexConfig


AGENTS_HEADER = """# Project Context (auto-generated by claudex)
# This file gives you full context about the project, the developer's preferences,
# coding standards, active tasks, and lessons learned. You are the REVIEWER.
# Your job: find bugs, security holes, logic errors, missed edge cases.
# Be direct. No filler. If it's clean, say so in one line.

"""

REVIEW_DIRECTIVE = """
---
## Your Role

You are the code reviewer for this project. The developer is using Claude Code
as their primary coding agent. Every time they change code, you receive the diff.

Review rules:
- Find bugs, security vulnerabilities, logic errors, edge cases
- Be concise and direct
- Reference specific file:line when flagging issues
- Score each review 1-10
- Format your response EXACTLY as:
  VERDICT: [clean|minor|issues|critical]
  ISSUES:
  1. file.js:42 - Description of issue
  2. file.js:88 - Description of issue
  SCORE: X/10
  SUMMARY: One line summary

If the code is clean, respond with:
  VERDICT: clean
  SCORE: 10/10
  SUMMARY: No issues found
"""


def read_file_safe(path: Path) -> str:
    try:
        if path.exists() and path.is_file():
            content = path.read_text(encoding="utf-8", errors="ignore")
            if len(content) > 10000:
                content = content[:10000] + "\n\n[truncated]"
            return content
    except Exception:
        pass
    return ""


def get_git_log(project_dir: str, count: int = 15) -> str:
    try:
        result = subprocess.run(
            ["git", "log", f"--oneline", f"-{count}"],
            capture_output=True, text=True, cwd=project_dir, timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return ""


def get_git_branch(project_dir: str) -> str:
    try:
        result = subprocess.run(
            ["git", "branch", "--show-current"],
            capture_output=True, text=True, cwd=project_dir, timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"


def summarize_skills(claude_dir: Path) -> str:
    skills_dir = claude_dir / "skills"
    if not skills_dir.exists():
        return ""

    summaries = []
    for skill_dir in sorted(skills_dir.iterdir()):
        if skill_dir.is_dir():
            summaries.append(f"- {skill_dir.name}")
    if summaries:
        return "Installed skills:\n" + "\n".join(summaries)
    return ""


def build_agents_md(config: ClaudexConfig) -> str:
    project_dir = Path(config.project_dir)
    home = Path.home()
    claude_home = home / ".claude"

    sections = [AGENTS_HEADER]

    sections.append("## Project\n")
    sections.append(f"- Directory: {config.project_dir}")
    sections.append(f"- Branch: {get_git_branch(config.project_dir)}")
    sections.append("")

    git_log = get_git_log(config.project_dir)
    if git_log:
        sections.append("## Recent Commits\n")
        sections.append(f"```\n{git_log}\n```\n")

    global_claude_md = claude_home / "CLAUDE.md"
    content = read_file_safe(global_claude_md)
    if content:
        sections.append("## Developer Preferences (from CLAUDE.md)\n")
        sections.append(content)
        sections.append("")

    primer = claude_home / "primer.md"
    content = read_file_safe(primer)
    if content:
        sections.append("## Current State (from primer.md)\n")
        sections.append(content)
        sections.append("")

    project_claude_md = project_dir / ".claude" / "CLAUDE.md"
    content = read_file_safe(project_claude_md)
    if content:
        sections.append("## Project-Level Instructions\n")
        sections.append(content)
        sections.append("")

    lessons = project_dir / "tasks" / "lessons.md"
    content = read_file_safe(lessons)
    if content:
        sections.append("## Lessons Learned\n")
        sections.append(content)
        sections.append("")

    todo = project_dir / "tasks" / "todo.md"
    content = read_file_safe(todo)
    if content:
        sections.append("## Active Tasks\n")
        sections.append(content)
        sections.append("")

    skills = summarize_skills(claude_home)
    if skills:
        sections.append("## Developer Tooling\n")
        sections.append(skills)
        sections.append("")

    session_log = Path(config.claudex_dir) / "session-summary.md"
    content = read_file_safe(session_log)
    if content:
        sections.append("## Previous Session Summary\n")
        sections.append(content)
        sections.append("")

    sections.append(REVIEW_DIRECTIVE)

    return "\n".join(sections)


def sync_context(config: ClaudexConfig) -> Path:
    agents_md = build_agents_md(config)
    output_path = Path(config.claudex_dir) / "agents.md.generated"
    output_path.write_text(agents_md, encoding="utf-8")

    project_agents = Path(config.project_dir) / "AGENTS.md"
    project_agents.write_text(agents_md, encoding="utf-8")

    return output_path


def incremental_sync(config: ClaudexConfig) -> None:
    sync_context(config)
